### ISSUE TITLE
Add support for unique_id

### ISSUE THREAD

**Issue by martiesim** [RedMeKool/HA-Raspberry-pi-GPIO-PWM#15]
The homeassistant ui won't let me edit the entities that are created by this integration, because they don't have a unique_id.

Could you add support for unique_ids? Maybe generate them automatically or add the "unique_id" key as an optional key to the configuration something like:

```
light:
  - platform: rpi_gpio_pwm
    leds:
      - name: RPI Cooling Fan
        unique_id: rpi_cooling_fan
        pin: 13
        frequency: 25000
```
