### ISSUE TITLE
Question: is it possible to use PCA9685 ic PWM?

### ISSUE THREAD

**Issue by alim-akbashev** [RedMeKool/HA-Raspberry-pi-GPIO-PWM#9]
Hello,

Thanks for your efforts in continuing to support the rpi_gpio_pwm!

Before 2022.04 I used rpi_gpio_pwm for integration with i2c module PCA9685 connected directly to rpi with configuration like:
```
light:
  - platform: rpi_gpio_pwm
    leds:
      - name: Strip1
        driver: pca9685
        frequency: 1526
        pins: [0]
        type: simple
```

Obviously and unfortunately after deprecation of rpi_gpio_pwm from HA side it's not possible anymore.

So, my question is: is it possible to use this custom component with PCA9685? if no does someone have a plan to add support of this?

Thanks
